### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by rhangad** [michalzelinka/Xcode83onElCapitan#1]
MakeXcodeGr8Again crashes when I drag Xcode.app to the window. And also, how do I compile SideLoader?

**Comment by username0x0a** [comment]
I guess you are trying to patch an App Store version. Try launching `MakeXcodeGr8Again` it from the Terminal like this:

`sudo MakeXcodeGr8Again.app/Contents/MacOS/MakeXcodeGr8Again`

To compile `SideLoader` simply compile the appropriate target in the included project and find the resulting library somewhere in the `DerivedData` folder.
